### ISSUE TITLE
Use greenlight instead of dflow in the URLs of the apps

### ISSUE THREAD

**Issue by swcurran** [bcgov/dFlow#224]
Please update the config of dflow to use "greenlight" in the various instances (e.g. greenlight.orgbook.gov.bc.ca) .  The urls are live.  Wade has added the routes to OpenShift already.

**Comment by esune** [comment]
I chatted with @WadeBarnes and we decided to recap the steps that are required after a domain name change.

Preliminary steps:
- new DNS entries are created for the new `dev` and `test` base URLs.
- new routes matching the new DNS entries are created in OpenShift, using the appropriate CA certificates, for the web application service.

Agent updates:
- each agent needs to be updated to reflect the new domain names. This includes:
  1. updating the `APPLICATION_URL` field to reflect the new webapp URL.
  2. re-creating the route exposing the agent endpoint, used in the `ENDPOINT_URL` environment variable.
- if the ledger domain name was updated, the `LEDGER_URL` field will require updating as well. The ledger will at least need to be restarted in order to set the updated display name environment variable that drives the browser window name.


Please note: it is not possible to have two public URLs and configure the agents so that they use the one initially followed to reach them (e.g.: keep all the dFlow traffic on dFlow routes, and GreenLight on GreenLight routes), since the ledger only stores the one provided upon agent startup and registration.

Cleaning up:
- all old routes can be deleted at this point, if desired.

**Comment by esune** [comment]
`dev` and `test` environments have been updated to use the new URLs
